PREFIX nen2660: <https://w3id.org/nen2660/def#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dash: <http://datashapes.org/dash#>

SELECT ?classURI ?label WHERE {
    # selecteer klassen
    ?classURI rdf:type rdfs:Class ;
        # ... die niet abstract zijn
        dash:abstract false ;
        # ... die subklasse van Fysiek Object (NEN 2660) zijn, 
        # of een subklasse van een subklasse
        rdfs:subClassOf* nen2660:PhysicalObject ;
        # en selecteer het label
        skos:prefLabel ?label .
 }
