PREFIX nen2660: <https://w3id.org/nen2660/def#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dash: <http://datashapes.org/dash#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

select ?attributeURI ?attributeLabel ?attributeDefinition WHERE {
    # voor de klassen
    # of: vervang in software de variable die met $ begint => voor de de klasse
    $classURI rdf:type rdfs:Class ;
        dash:abstract false ;
        rdfs:subClassOf* nen2660:PhysicalObject .

    # voor de eigenschap(pen) via SHACL eigenschap-pad
    $classURI sh:property/sh:path ?attributeURI .

    # retourneer de naam
    OPTIONAL { ?attributeURI skos:prefLabel ?attributeLabel . }
    # retourneer de definitie
    OPTIONAL { ?attributeURI skos:definition ?attributeDefinition . }
    # retourneer de attribuut-grootheid (eenheid is opgeslagen in SHACL)
    OPTIONAL{ ?attribuut nen2660:hasQuantityKind/skos:prefLabel ?attributQuantityKind . }
}